language: objective-c

osx_image: xcode8.2
xcode_project: PersonalStuff.xcodeproj
xcode_scheme: PersonalStuffTests
xcode_sdk: iphonesimulator10.1

script:
  - xcodebuild -project PersonalStuff.xcodeproj -scheme PersonalStuffTests -sdk iphonesimulator build test | xcpretty
